paginate: 100
paginate_path: "/blog/page:num/"
baseurl: ''
permalink: /blog/post/:title
kramdown:
  input: GFM
  syntax_highlighter: rouge
markdown: redcarpet 
redcarpet:
  extensions: ["strikethrough"] 
gems: [jekyll-paginate, jekyll-gist]
